name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow for pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js for both client and server
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the version of Node.js you are using

    # Install dependencies for the client
    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    # Install dependencies for the server
    - name: Install server dependencies
      working-directory: ./server
      run: npm install

    # Build the client if necessary (e.g., for Vue.js)
    - name: Build client
      working-directory: ./client
      run: npm run build

    # Optionally: Build Docker images for both client and server (if using Docker)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for client
      working-directory: ./client
      run: |
        docker build -t stiliyan7/micro-blog-client:latest .
        docker tag stiliyan7/micro-blog-client:latest stiliyan7/micro-blog-client:latest
        docker push stiliyan7/micro-blog-client:latest

    - name: Build Docker image for server
      working-directory: ./server
      run: |
        docker build -t stiliyan7/micro-blog-server:latest .
        docker tag stiliyan7/micro-blog-server:latest stiliyan7/micro-blog-server:latest
        docker push stiliyan7/micro-blog-server:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render (Server)
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cuju21qj1k6c73d2e3n0?key=${{ secrets.RENDER_API_KEY }}"
  
      - name: Deploy to Render (Client)
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cujuph3tq21c73e2e110?key=${{ secrets.RENDER_API_KEY }}"

